### ISSUE TITLE
Fix: CSS 수정 요청

### ISSUE THREAD

**Issue by hyemch** [Hanaro-Trolly/ONE-HADA-FE#16]
# Description
- CSS 수정 요청사항 입니다. 

# ✅ To-do
 - [x] nav bar 넓이 고정
 - [x] 모달 최대/ 최소 크기 고정
 - [x] 바로가기 카드 즐겨찾기/ 체크박스 크기 및 위치
 - [x] 전체적인 여백 맞추기
